version: '3.8'

services:
	db:
		image: mongo
		container_name: db
		restart: always
		environment:
			-MONGO_INITDB_ROOT_USERNAME=rodglins
			-MONGO_INITDB_ROOT_PASSWORD=rodglins
		ports:
			- "27017:27017"
		volumes:
			- /home/azureuser/mongo/dbdata:/data/db